name: Pull Request CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Build Docker image
      run: |
        DOCKERFILE_PATH=$(find -type f -name Dockerfile)
        docker build -t prog:latest -f $DOCKERFILE_PATH .
        
    - name: Test with Docker
      run: docker run prog

    
